# FROM coolcat647/ros-pytorch:cuda10.0
FROM coolcat647/ros-pytorch:cuda9.0

# Base image link: https://hub.docker.com/r/coolcat647/ros-pytorch/dockerfile
# Include:
# - Ubuntu 16.04 amd64 architecture
# - Nvidia cuda 9.0/ 10.0 (depend on tag)
# - ROS kinetic --> you can check it out by ${ROS_DISTRO} variable!
# - Pytorch 1.0.1 / 1.2.0 (depend on tag)
# - Jupyter
# - Python2.7 package: numpy, opencv, pandas etc. 

SHELL ["/bin/bash", "-c"]

# ROS packages
RUN apt-get install -y ros-${ROS_DISTRO}-hardware-interface \
    ros-${ROS_DISTRO}-velocity-controllers \
    ros-${ROS_DISTRO}-controller-manager \
    ros-${ROS_DISTRO}-joint-trajectory-controller \
    ros-${ROS_DISTRO}-joint-state-controller \
    ros-${ROS_DISTRO}-effort-controllers \
    ros-${ROS_DISTRO}-industrial-msgs \
    ros-${ROS_DISTRO}-soem \
    ros-${ROS_DISTRO}-hardware-interface \
    ros-${ROS_DISTRO}-image-transport \
    ros-${ROS_DISTRO}-cv-bridge \
    ros-${ROS_DISTRO}-gazebo-ros \
    ros-${ROS_DISTRO}-gazebo-ros-control \
    ros-${ROS_DISTRO}-pcl-conversions \
    ros-${ROS_DISTRO}-pcl-ros \
    ros-${ROS_DISTRO}-ddynamic-reconfigure \
    libopencv-dev \
    libv4l-dev \
    python-pymodbus \
    python-lxml \
    && rm -rf /var/lib/list

# Intel librealsense2 SDK
RUN echo 'deb http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo xenial main' | sudo tee /etc/apt/sources.list.d/realsense-public.list && \
    apt-key adv --keyserver keys.gnupg.net --recv-key 6F3EFCDE && \
    apt-get update && \
    apt-get install -y librealsense2-dkms \
    librealsense2-utils \
    librealsense2-dev \
    librealsense2-dbg \
    && rm -rf /var/lib/list

# Python packages
RUN pip install xmltodict kitti2bag sklearn pyassimp==4.1.3


# Create a new user
ENV USER developer
RUN useradd -m -d /home/${USER} ${USER} -p "" \
 && chown -R ${USER} /home/${USER} /root/ && adduser ${USER} sudo
USER ${USER}

RUN sudo rm /etc/ros/rosdep/sources.list.d/20-default.list && \
    sudo rosdep init && rosdep update && \
    echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> /home/${USER}/.bashrc && \
    source /home/${USER}/.bashrc

CMD ["/bin/bash"]
